import React, { useEffect } from 'react';
import { Transaction, UnitType } from '../types';
import { X, Printer } from 'lucide-react';
import { Button } from './Button';
import { formatDateTime } from '../utils';

interface InvoiceModalProps {
  transaction: Transaction;
  onClose: () => void;
  isOpen: boolean;
}

export const InvoiceModal: React.FC<InvoiceModalProps> = ({ transaction, onClose, isOpen }) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm print:p-0 print:bg-white print:static">
      {/* Print Styles */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #receipt-content, #receipt-content * {
            visibility: visible;
          }
          #receipt-content {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            margin: 0;
            padding: 20px;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      <div className="bg-white w-full max-w-md rounded-xl shadow-2xl flex flex-col max-h-[90vh] overflow-hidden animate-in fade-in zoom-in duration-200 print:shadow-none print:max-h-none print:w-full print:max-w-none">

        {/* Header - Screen Only */}
        <div className="p-4 border-b flex justify-between items-center bg-slate-50 print:hidden">
          <h2 className="font-bold text-lg">Transaction Receipt</h2>
          <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Receipt Content */}
        <div className="p-8 overflow-y-auto flex-1 font-mono text-sm" id="receipt-content">
          <div className="text-center mb-6">
            <h1 className="text-2xl font-bold tracking-widest mb-1">SightBill</h1>
            <p className="text-slate-500">RV College Bengaluru</p>
            <p className="text-slate-500">Final EL Project</p>
          </div>

          <div className="border-b-2 border-dashed border-slate-300 pb-4 mb-4">
            <div className="flex justify-between">
              <span className="text-slate-500">Date:</span>
              <span>{formatDateTime(transaction.timestamp)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Receipt #:</span>
              <span className="font-mono">{transaction.id.toUpperCase()}</span>
            </div>
          </div>

          <table className="w-full mb-6">
            <thead>
              <tr className="text-left text-slate-500 border-b border-slate-200">
                <th className="pb-2 font-normal">Item</th>
                <th className="pb-2 font-normal text-right">Qty</th>
                <th className="pb-2 font-normal text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              {transaction.items.map(item => (
                <tr key={item.id} className="border-b border-slate-100 last:border-0">
                  <td className="py-2">
                    <div className="font-bold">{item.name}</div>
                    <div className="text-xs text-slate-400">
                      ₹{(item.unitPrice || 0).toFixed(2)}/{item.unit || 'unit'}
                      {item.isEdited && <span className="ml-1 text-orange-500">[MODIFIED]</span>}
                    </div>
                  </td>
                  <td className="py-2 text-right align-top">
                    {(item.quantity || 0).toFixed(item.unit === UnitType.KG ? 3 : 0)}
                  </td>
                  <td className="py-2 text-right align-top font-medium">
                    ₹{(item.totalPrice || 0).toFixed(2)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="border-t-2 border-slate-900 pt-4 mb-8">
            <div className="flex justify-between text-xl font-bold">
              <span>TOTAL</span>
              <span>₹{(transaction.total || 0).toFixed(2)}</span>
            </div>
            {transaction.hasAnomalies && (
              <div className="mt-2 text-xs text-center border border-slate-200 p-1 rounded text-slate-500">
                * Transaction Flagged for Internal Review
              </div>
            )}
          </div>

          <div className="text-center text-xs text-slate-400">
            <p>Thank you for shopping with us!</p>
            <p className="mt-1">Generated by SightBill</p>
          </div>
        </div>

        {/* Footer Actions - Screen Only */}
        <div className="p-4 border-t bg-slate-50 flex gap-3 print:hidden">
          <Button variant="outline" className="flex-1" onClick={onClose}>Close</Button>
          <Button variant="primary" className="flex-1" onClick={handlePrint} icon={<Printer size={18} />}>
            Print Receipt
          </Button>
        </div>
      </div>
    </div>
  );
};